name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: codeigniter_db
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_password
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PHP version from composer.json
        id: php-version
        run: |
          PHP_VERSION=$(jq -r '.require.php' composer.json | sed 's/>=\|>\|<\|<=\|~\|\^\|=//g' | cut -d'|' -f1 | cut -d' ' -f1)
          echo "version=$PHP_VERSION" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.php-version.outputs.version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysqli

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create environment file
        run: |
          cp env.example .env
          echo "CI_ENV=testing" >> .env

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -P"3307" -u"root" -p"root" --silent; do
            echo 'waiting for mysqld to be connectable...'
            sleep 2
          done

      - name: Set up database
        run: |
          mysql -h 127.0.0.1 -P 3307 -u root -proot -e "CREATE DATABASE IF NOT EXISTS codeigniter_db;"
          mysql -h 127.0.0.1 -P 3307 -u root -proot -e "GRANT ALL PRIVILEGES ON codeigniter_db.* TO 'ci_user'@'%' IDENTIFIED BY 'ci_password';"
          mysql -h 127.0.0.1 -P 3307 -u root -proot -e "FLUSH PRIVILEGES;"

      - name: Create database tables
        run: |
          mysql -h 127.0.0.1 -P 3307 -u ci_user -pci_password codeigniter_db < database/init/01_create_posts_table.sql

      - name: Run tests
        run: composer test
